//
//  TinyImageNetClasses.swift
//  contexter
//
//  Created by Aleksey Sevruk on 11/20/17.
//  Copyright © 2017 Aleksey Sevruk. All rights reserved.
//

import Foundation

class TinyImageNetClasses {
    var dict = [Int: String]()
    
    func getLabel(cls: Int) -> String {
        let label = dict[cls]
        return label == nil ? "" : label!
    }
    
    func getSize() -> Int {
        return dict.count
    }
    
    public init() {
        dict[0] = "goldfish, Carassius auratus"
        dict[1] = "European fire salamander, Salamandra salamandra"
        dict[2] = "bullfrog, Rana catesbeiana"
        dict[3] = "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui"
        dict[4] = "American alligator, Alligator mississipiensis"
        dict[5] = "boa constrictor, Constrictor constrictor"
        dict[6] = "trilobite"
        dict[7] = "scorpion"
        dict[8] = "black widow, Latrodectus mactans"
        dict[9] = "tarantula"
        dict[10] = "centipede"
        dict[11] = "goose"
        dict[12] = "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus"
        dict[13] = "jellyfish"
        dict[14] = "brain coral"
        dict[15] = "snail"
        dict[16] = "slug"
        dict[17] = "sea slug, nudibranch"
        dict[18] = "American lobster, Northern lobster, Maine lobster, Homarus americanus"
        dict[19] = "spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish"
        dict[20] = "black stork, Ciconia nigra"
        dict[21] = "king penguin, Aptenodytes patagonica"
        dict[22] = "albatross, mollymawk"
        dict[23] = "dugong, Dugong dugon"
        dict[24] = "Chihuahua"
        dict[25] = "Yorkshire terrier"
        dict[26] = "golden retriever"
        dict[27] = "Labrador retriever"
        dict[28] = "German shepherd, German shepherd dog, German police dog, alsatian"
        dict[29] = "standard poodle"
        dict[30] = "tabby, tabby cat"
        dict[31] = "Persian cat"
        dict[32] = "Egyptian cat"
        dict[33] = "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor"
        dict[34] = "lion, king of beasts, Panthera leo"
        dict[35] = "brown bear, bruin, Ursus arctos"
        dict[36] = "ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle"
        dict[37] = "fly"
        dict[38] = "bee"
        dict[39] = "grasshopper, hopper"
        dict[40] = "walking stick, walkingstick, stick insect"
        dict[41] = "cockroach, roach"
        dict[42] = "mantis, mantid"
        dict[43] = "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk"
        dict[44] = "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus"
        dict[45] = "sulphur butterfly, sulfur butterfly"
        dict[46] = "sea cucumber, holothurian"
        dict[47] = "guinea pig, Cavia cobaya"
        dict[48] = "hog, pig, grunter, squealer, Sus scrofa"
        dict[49] = "ox"
        dict[50] = "bison"
        dict[51] = "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis"
        dict[52] = "gazelle"
        dict[53] = "Arabian camel, dromedary, Camelus dromedarius"
        dict[54] = "orangutan, orang, orangutang, Pongo pygmaeus"
        dict[55] = "chimpanzee, chimp, Pan troglodytes"
        dict[56] = "baboon"
        dict[57] = "African elephant, Loxodonta africana"
        dict[58] = "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens"
        dict[59] = "abacus"
        dict[60] = "academic gown, academic robe, judge's robe"
        dict[61] = "altar"
        dict[62] = "apron"
        dict[63] = "backpack, back pack, knapsack, packsack, rucksack, haversack"
        dict[64] = "bannister, banister, balustrade, balusters, handrail"
        dict[65] = "barbershop"
        dict[66] = "barn"
        dict[67] = "barrel, cask"
        dict[68] = "basketball"
        dict[69] = "bathtub, bathing tub, bath, tub"
        dict[70] = "beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon"
        dict[71] = "beacon, lighthouse, beacon light, pharos"
        dict[72] = "beaker"
        dict[73] = "beer bottle"
        dict[74] = "bikini, two-piece"
        dict[75] = "binoculars, field glasses, opera glasses"
        dict[76] = "birdhouse"
        dict[77] = "bow tie, bow-tie, bowtie"
        dict[78] = "brass, memorial tablet, plaque"
        dict[79] = "broom"
        dict[80] = "bucket, pail"
        dict[81] = "bullet train, bullet"
        dict[82] = "butcher shop, meat market"
        dict[83] = "candle, taper, wax light"
        dict[84] = "cannon"
        dict[85] = "cardigan"
        dict[86] = "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM"
        dict[87] = "CD player"
        dict[88] = "chain"
        dict[89] = "chest"
        dict[90] = "Christmas stocking"
        dict[91] = "cliff dwelling"
        dict[92] = "computer keyboard, keypad"
        dict[93] = "confectionery, confectionary, candy store"
        dict[94] = "convertible"
        dict[95] = "crane"
        dict[96] = "dam, dike, dyke"
        dict[97] = "desk"
        dict[98] = "dining table, board"
        dict[99] = "drumstick"
        dict[100] = "dumbbell"
        dict[101] = "flagpole, flagstaff"
        dict[102] = "fountain"
        dict[103] = "freight car"
        dict[104] = "frying pan, frypan, skillet"
        dict[105] = "fur coat"
        dict[106] = "gasmask, respirator, gas helmet"
        dict[107] = "go-kart"
        dict[108] = "gondola"
        dict[109] = "hourglass"
        dict[110] = "iPod"
        dict[111] = "jinrikisha, ricksha, rickshaw"
        dict[112] = "kimono"
        dict[113] = "lampshade, lamp shade"
        dict[114] = "lawn mower, mower"
        dict[115] = "lifeboat"
        dict[116] = "limousine, limo"
        dict[117] = "magnetic compass"
        dict[118] = "maypole"
        dict[119] = "military uniform"
        dict[120] = "miniskirt, mini"
        dict[121] = "moving van"
        dict[122] = "nail"
        dict[123] = "neck brace"
        dict[124] = "obelisk"
        dict[125] = "oboe, hautboy, hautbois"
        dict[126] = "organ, pipe organ"
        dict[127] = "parking meter"
        dict[128] = "pay-phone, pay-station"
        dict[129] = "picket fence, paling"
        dict[130] = "pill bottle"
        dict[131] = "plunger, plumber's helper"
        dict[132] = "pole"
        dict[133] = "police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria"
        dict[134] = "poncho"
        dict[135] = "pop bottle, soda bottle"
        dict[136] = "potter's wheel"
        dict[137] = "projectile, missile"
        dict[138] = "punching bag, punch bag, punching ball, punchball"
        dict[139] = "reel"
        dict[140] = "refrigerator, icebox"
        dict[141] = "remote control, remote"
        dict[142] = "rocking chair, rocker"
        dict[143] = "rugby ball"
        dict[144] = "sandal"
        dict[145] = "school bus"
        dict[146] = "scoreboard"
        dict[147] = "sewing machine"
        dict[148] = "snorkel"
        dict[149] = "sock"
        dict[150] = "sombrero"
        dict[151] = "space heater"
        dict[152] = "spider web, spider's web"
        dict[153] = "sports car, sport car"
        dict[154] = "steel arch bridge"
        dict[155] = "stopwatch, stop watch"
        dict[156] = "sunglasses, dark glasses, shades"
        dict[157] = "suspension bridge"
        dict[158] = "swimming trunks, bathing trunks"
        dict[159] = "syringe"
        dict[160] = "teapot"
        dict[161] = "teddy, teddy bear"
        dict[162] = "thatch, thatched roof"
        dict[163] = "torch"
        dict[164] = "tractor"
        dict[165] = "triumphal arch"
        dict[166] = "trolleybus, trolley coach, trackless trolley"
        dict[167] = "turnstile"
        dict[168] = "umbrella"
        dict[169] = "vestment"
        dict[170] = "viaduct"
        dict[171] = "volleyball"
        dict[172] = "water jug"
        dict[173] = "water tower"
        dict[174] = "wok"
        dict[175] = "wooden spoon"
        dict[176] = "comic book"
        dict[177] = "plate"
        dict[178] = "guacamole"
        dict[179] = "ice cream, icecream"
        dict[180] = "ice lolly, lolly, lollipop, popsicle"
        dict[181] = "pretzel"
        dict[182] = "mashed potato"
        dict[183] = "cauliflower"
        dict[184] = "bell pepper"
        dict[185] = "mushroom"
        dict[186] = "orange"
        dict[187] = "lemon"
        dict[188] = "banana"
        dict[189] = "pomegranate"
        dict[190] = "meat loaf, meatloaf"
        dict[191] = "pizza, pizza pie"
        dict[192] = "potpie"
        dict[193] = "espresso"
        dict[194] = "alp"
        dict[195] = "cliff, drop, drop-off"
        dict[196] = "coral reef"
        dict[197] = "lakeside, lakeshore"
        dict[198] = "seashore, coast, seacoast, sea-coast"
        dict[199] = "acorn"
    }
}
